Repository AY2425S1-CS2103T-W14-1/tp, pull requests merged in 2024-10, with the labels that each got.

#15 Add Pravein's photo
  docs/images/prave1n.png
Labels: type.Task

#14 Add Jian Yi's photo
  docs/images/ngjianyi.png
Labels: type.Task

#5 Add Jianzhi's photo
  build.gradle
  docs/images/cjianzhi.png
Labels: type.Task

#13 Add Linkes's photo
  docs/images/linkesv.png
Labels: type.Task

#21 Update AboutUs.md with Pravein's info
  docs/AboutUs.md
Labels: type.Task

#24 Add Jian Yi about us details
  docs/AboutUs.md
Labels: type.Task

#19 Update AboutUs.md
  docs/AboutUs.md
Labels: type.Task

#26 Update AboutUs.md
  docs/AboutUs.md
Labels: type.Task

#25 Update AboutUs.md
  docs/AboutUs.md
Labels: type.Task

#30 Update README.md
  README.md
  docs/AboutUs.md
  docs/images/Ui.png
Labels: type.Task

#32 Update value proposition in Developer's guide
  docs/DeveloperGuide.md
Labels: type.Task

#31 Add user stories to DG
  docs/DeveloperGuide.md
Labels: type.Task

#36 update developer guide use cases
  docs/DeveloperGuide.md
Labels: type.Task

#38 Delivery feature increament
  src/main/java/seedu/address/model/delivery/Delivery.java
  src/main/java/seedu/address/model/delivery/DeliveryDetail.java
  src/main/java/seedu/address/model/delivery/DeliveryStatus.java
  src/main/java/seedu/address/model/delivery/DeliveryTime.java
Labels: type.Task

#41 Create Product class
  src/main/java/seedu/address/model/product/Product.java
Labels: priority.High

#43 create Company class
  src/main/java/seedu/address/model/person/Company.java
Labels: type.Task, priority.High

#49 Model and Storage created for deliveries
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/delivery/Cost.java
  src/main/java/seedu/address/model/delivery/Delivery.java
  src/main/java/seedu/address/model/delivery/DeliveryDetail.java
  src/main/java/seedu/address/model/delivery/DeliveryTime.java
  src/main/java/seedu/address/model/delivery/Description.java
  src/main/java/seedu/address/model/delivery/Quantity.java
  src/main/java/seedu/address/model/delivery/Status.java
  src/main/java/seedu/address/model/delivery/Time.java
  src/main/java/seedu/address/model/delivery/UniqueDeliveryList.java
  src/main/java/seedu/address/model/delivery/exceptions/DeliveryNotFoundException.java
  src/main/java/seedu/address/model/delivery/exceptions/DuplicateDeliveryException.java
  src/main/java/seedu/address/model/product/Product.java
  src/main/java/seedu/address/storage/JsonAdaptedDelivery.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/delivery/CostTest.java
  src/test/java/seedu/address/model/delivery/DeliveryTest.java
  src/test/java/seedu/address/model/delivery/QuantityTest.java
  src/test/java/seedu/address/model/delivery/TimeTest.java
  src/test/java/seedu/address/model/delivery/UniqueDeliveryListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedDeliveryTest.java
  src/test/java/seedu/address/testutil/DeliveryBuilder.java
  src/test/java/seedu/address/testutil/TypicalDeliveries.java
Labels: type.Task, priority.High

#54 Delete delivery command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteDeliveryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteDeliveryCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteDeliveryCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteDeliveryCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Task, priority.High

#57 Mark delivery command
  src/main/java/seedu/address/logic/commands/MarkDeliveryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MarkDeliveryCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/delivery/Delivery.java
  src/main/java/seedu/address/model/delivery/UniqueDeliveryList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkDeliveryCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/MarkDeliveryCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Task, priority.High

#62 Add Supplier object, DeleteSupplierCommand, MarkSupplierCommand, and their corresponding Parsers
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteSupplierCommand.java
  src/main/java/seedu/address/logic/commands/MarkSupplierCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteSupplierCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkSupplierCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/supplier/Company.java
  src/main/java/seedu/address/model/supplier/Supplier.java
  src/main/java/seedu/address/model/supplier/SupplierContact.java
  src/main/java/seedu/address/model/supplier/SupplierEmail.java
  src/main/java/seedu/address/model/supplier/SupplierName.java
  src/main/java/seedu/address/model/supplier/SupplierNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/supplier/SupplierStatus.java
  src/main/java/seedu/address/model/supplier/UniqueSupplierList.java
  src/main/java/seedu/address/model/supplier/exceptions/DuplicateSupplierException.java
  src/main/java/seedu/address/model/supplier/exceptions/SupplierNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedSupplier.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteSupplierCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkSupplierCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/JsonAdaptedSupplierTest.java
  src/test/java/seedu/address/testutil/SupplierBuilder.java
  src/test/java/seedu/address/testutil/TypicalSuppliers.java
Labels: type.Task, priority.High

#64 Revert "Add Supplier object, DeleteSupplierCommand, MarkSupplierCommand, and their corresponding Parsers"
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteSupplierCommand.java
  src/main/java/seedu/address/logic/commands/MarkSupplierCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteSupplierCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkSupplierCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/Company.java
  src/main/java/seedu/address/model/supplier/Supplier.java
  src/main/java/seedu/address/model/supplier/SupplierContact.java
  src/main/java/seedu/address/model/supplier/SupplierEmail.java
  src/main/java/seedu/address/model/supplier/SupplierName.java
  src/main/java/seedu/address/model/supplier/SupplierNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/supplier/SupplierStatus.java
  src/main/java/seedu/address/model/supplier/UniqueSupplierList.java
  src/main/java/seedu/address/model/supplier/exceptions/DuplicateSupplierException.java
  src/main/java/seedu/address/model/supplier/exceptions/SupplierNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedSupplier.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteSupplierCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkSupplierCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/JsonAdaptedSupplierTest.java
  src/test/java/seedu/address/testutil/SupplierBuilder.java
  src/test/java/seedu/address/testutil/TypicalSuppliers.java
Labels: type.Task

#72 Split MainWindow to include deliveries
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeleteDeliveryCommand.java
  src/main/java/seedu/address/logic/commands/MarkDeliveryCommand.java
  src/main/java/seedu/address/ui/DeliveryCard.java
  src/main/java/seedu/address/ui/DeliveryListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DeliveryListCard.fxml
  src/main/resources/view/DeliveryListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/DeleteDeliveryCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkDeliveryCommandTest.java
Labels: type.Task, priority.High

#71 Add company product field
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/product/Product.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedProduct.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#75 Edit UI to display person with new fields
  src/main/java/seedu/address/logic/commands/AddDeliveryCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/PersonListCard.fxml
Labels: priority.High

#79 Beautify UI
  src/main/java/seedu/address/logic/parser/AddDeliveryCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/delivery/DateTime.java
  src/main/java/seedu/address/model/delivery/Delivery.java
  src/main/java/seedu/address/storage/JsonAdaptedDelivery.java
  src/main/java/seedu/address/ui/DeliveryCard.java
  src/main/java/seedu/address/ui/DeliveryListPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address.png
  src/main/resources/images/cost.png
  src/main/resources/images/datetime.png
  src/main/resources/images/email.png
  src/main/resources/images/icon.png
  src/main/resources/images/person.png
  src/main/resources/images/phone.png
  src/main/resources/images/quantity.png
  src/main/resources/view/DefaultTheme.css
  src/main/resources/view/DeliveryListCard.fxml
  src/main/resources/view/DeliveryListPanel.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/logic/parser/AddDeliveryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/delivery/DateTimeTest.java
  src/test/java/seedu/address/model/delivery/TimeTest.java
  src/test/java/seedu/address/storage/JsonAdaptedDeliveryTest.java
  src/test/java/seedu/address/testutil/DeliveryBuilder.java
Labels: type.Task, priority.High

#81 Fix supplier command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddDeliveryCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteDeliveryCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSupplierCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkDeliveryCommand.java
  src/main/java/seedu/address/logic/commands/MarkSupplierCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/SupplierStatus.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/DeliveryUtil.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#83 Remove supplier status prefix
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#85 Update UI
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddDeliveryCommand.java
  src/main/java/seedu/address/logic/parser/AddDeliveryCommandParser.java
  src/main/java/seedu/address/model/delivery/Delivery.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Task, priority.High

#86 Add JUnit tests for SupplierIndex class
  src/test/java/seedu/address/model/delivery/SupplierIndexTest.java
Labels: priority.High

#91 Upcoming Command feature
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/UpcomingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UpcomingCommandParser.java
  src/main/java/seedu/address/model/delivery/DateTime.java
  src/main/java/seedu/address/model/delivery/DateTimeBeforeInputDatePredicate.java
  src/main/java/seedu/address/model/delivery/Delivery.java
  src/main/java/seedu/address/model/delivery/DeliveryIsUpcomingPredicate.java
  src/main/java/seedu/address/model/delivery/DeliveryStatusMatchInputPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedDelivery.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/UpcomingCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/UpcomingCommandParserTest.java
  src/test/java/seedu/address/model/delivery/DateTimeBeforeInputDatePredicateTest.java
  src/test/java/seedu/address/model/delivery/DateTimeTest.java
  src/test/java/seedu/address/model/delivery/DeliveryIsUpcomingPredicateTest.java
  src/test/java/seedu/address/model/delivery/DeliveryStatusMatchInputPredicateTest.java
  src/test/java/seedu/address/model/delivery/DeliveryTest.java
  src/test/java/seedu/address/storage/JsonAdaptedDeliveryTest.java
  src/test/java/seedu/address/testutil/DeliveryBuilder.java
  src/test/java/seedu/address/testutil/TypicalDeliveries.java
Labels: priority.High

#89 Feature sort deliveries
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/SortDeliveryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortDeliveryCommandParser.java
  src/main/java/seedu/address/logic/parser/SortOrder.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/delivery/DeliverySortBy.java
  src/main/java/seedu/address/model/delivery/DeliverySortComparator.java
  src/main/java/seedu/address/model/delivery/DeliverySortCostComparator.java
  src/main/java/seedu/address/model/delivery/DeliverySortDateTimeComparator.java
  src/main/java/seedu/address/model/delivery/DeliverySortStatusComparator.java
  src/main/java/seedu/address/model/delivery/Description.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddDeliveryCommandTest.java
  src/test/java/seedu/address/logic/commands/SortDeliveryCommandTest.java
  src/test/java/seedu/address/logic/parser/SortDeliveryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortOrderTest.java
  src/test/java/seedu/address/model/delivery/DeliverySortByTest.java
  src/test/java/seedu/address/model/delivery/DeliverySortCostComparatorTest.java
  src/test/java/seedu/address/model/delivery/DeliverySortDateTimeComparatorTest.java
  src/test/java/seedu/address/model/delivery/DeliverySortStatusComparatorTest.java
Labels: type.Task, priority.High

#94 Find delivery by date, status, product or supplier
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindDeliveryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindDeliveryCommandParser.java
  src/main/java/seedu/address/model/delivery/Delivery.java
  src/main/java/seedu/address/model/delivery/DeliveryDatePredicate.java
  src/main/java/seedu/address/model/delivery/DeliveryProductPredicate.java
  src/main/java/seedu/address/model/delivery/DeliverySupplierPredicate.java
  src/test/java/seedu/address/logic/commands/FindDeliveryCommandTest.java
  src/test/java/seedu/address/logic/commands/SortDeliveryCommandTest.java
  src/test/java/seedu/address/logic/commands/UpcomingCommandTest.java
  src/test/java/seedu/address/logic/parser/FindDeliveryCommandParserTest.java
  src/test/java/seedu/address/model/delivery/DeliveryDatePredicateTest.java
  src/test/java/seedu/address/model/delivery/DeliveryProductPredicateTest.java
  src/test/java/seedu/address/model/delivery/DeliverySupplierPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalDeliveries.java
Labels: type.Task, priority.High

#103 Fix UI update bug
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/FindDeliveryCommand.java
  src/main/java/seedu/address/logic/commands/FindSupplierCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/SupplierFindBy.java
  src/main/java/seedu/address/model/person/SupplierSortNameComparator.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddDeliveryCommandTest.java
Labels: type.Bug, priority.High, severity.High

#108 Update UG with delete supplier and mark supplier command
  docs/UserGuide.md
Labels: priority.High

#111 Update User guide for add command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddDeliveryCommand.java
Labels: priority.High

#107 Update UserGuide with Mark and Delete commands for deliveries
  docs/UserGuide.md
Labels: type.Task, priority.High

#113 Update user guide
  docs/UserGuide.md
  docs/images/Ui.png
Labels: type.Enhancement, priority.Medium

#114 Add images to UG
  docs/UserGuide.md
  docs/images/addDeliveryCommand.png
  docs/images/addSupplierCommand.png
  docs/images/deleteDeliveryCommand.png
  docs/images/deleteSupplierCommand.png
  docs/images/markDeliveryCommand.png
  docs/images/markSupplierCommand.png
Labels: type.Enhancement, priority.Medium

#116 Update Storage Diagram
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Enhancement, priority.High

#118 Update UML class diagram for Model
  docs/diagrams/BetterModelClassDiagram.puml
Labels: priority.High

#120 Update model class diagram supplier fields
  docs/diagrams/BetterModelClassDiagram.puml
Labels: type.Task
