Repository AY2425S1-CS2103T-W14-1/tp, pull requests merged in 2024-11, with the labels that each got.

#124 Update upcoming feature to include date before parameter
  src/main/java/seedu/address/logic/commands/UpcomingCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/UpcomingCommandParser.java
  src/main/java/seedu/address/model/delivery/DateTime.java
  src/main/java/seedu/address/model/delivery/DateTimeAfterInputDatePredicate.java
  src/main/java/seedu/address/model/delivery/Delivery.java
  src/main/java/seedu/address/model/delivery/DeliveryIsUpcomingAfterPredicate.java
  src/main/java/seedu/address/model/delivery/DeliveryIsUpcomingBeforePredicate.java
  src/test/java/seedu/address/logic/commands/UpcomingCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/UpcomingCommandParserTest.java
  src/test/java/seedu/address/model/delivery/DateTimeAfterInputDatePredicateTest.java
  src/test/java/seedu/address/model/delivery/DeliveryIsUpcomingAfterPredicateTest.java
  src/test/java/seedu/address/model/delivery/DeliveryIsUpcomingBeforePredicateTest.java
Labels: priority.High

#128 Add delete supplier sequence diagram
  docs/diagrams/DeleteSupplierSequenceDiagram.puml
Labels: type.Task

#126 Update List Command
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ListAllCommand.java
  src/main/java/seedu/address/logic/commands/ListDeliveryCommand.java
  src/main/java/seedu/address/logic/commands/ListSupplierCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListAllCommandTest.java
  src/test/java/seedu/address/logic/commands/ListSupplierCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task, priority.High

#127 Delivery class constructor
  src/main/java/seedu/address/logic/commands/AddDeliveryCommand.java
  src/main/java/seedu/address/logic/parser/AddDeliveryCommandParser.java
  src/main/java/seedu/address/model/delivery/Delivery.java
  src/main/java/seedu/address/model/delivery/DeliveryWrapper.java
  src/test/java/seedu/address/logic/commands/AddDeliveryCommandTest.java
  src/test/java/seedu/address/logic/parser/AddDeliveryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/delivery/DeliveryWrapperTest.java
  src/test/java/seedu/address/storage/JsonAdaptedDeliveryTest.java
  src/test/java/seedu/address/testutil/DeliveryBuilder.java
  src/test/java/seedu/address/testutil/DeliveryUtil.java
  src/test/java/seedu/address/testutil/TypicalDeliveries.java
  src/test/java/seedu/address/testutil/TypicalDeliveryWrappers.java
Labels: priority.High

#163 FIx delete and mark commands failing after sorting
  src/main/java/seedu/address/logic/commands/AddDeliveryCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteDeliveryCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSupplierCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkDeliveryCommand.java
  src/main/java/seedu/address/logic/commands/MarkSupplierCommand.java
  src/test/java/seedu/address/logic/commands/AddDeliveryCommandTest.java
Labels: type.Bug, alpha-bug

#166 Fix Alpha Bugs assigned to me
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddSupplierCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindDeliveryCommand.java
  src/main/java/seedu/address/logic/commands/FindSupplierCommand.java
  src/main/java/seedu/address/logic/parser/AddSupplierCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindSupplierCommandParser.java
  src/main/java/seedu/address/model/delivery/Delivery.java
  src/main/java/seedu/address/model/delivery/Quantity.java
  src/main/java/seedu/address/model/product/Product.java
  src/main/java/seedu/address/model/supplier/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/supplier/Supplier.java
  src/main/java/seedu/address/model/supplier/predicates/NameContainsKeywordPredicate.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddSupplierCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindSupplierCommandTest.java
  src/test/java/seedu/address/logic/parser/AddSupplierCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindSupplierCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/delivery/QuantityTest.java
  src/test/java/seedu/address/model/supplier/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/supplier/predicate/NameContainsKeywordPredicateTest.java
  src/test/java/seedu/address/testutil/SupplierUtil.java
Labels: priority.High, alpha-bug

#162 Fix bugs in FindDeliveryCommand and MarkDeliveryCommand
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindDeliveryCommand.java
  src/main/java/seedu/address/logic/commands/MarkDeliveryCommand.java
  src/test/java/seedu/address/logic/commands/MarkDeliveryCommandTest.java
Labels: type.Bug, priority.High, alpha-bug

#164 Fix bugs in Add Delivery and Upcoming Command
  src/main/java/seedu/address/logic/commands/AddDeliveryCommand.java
  src/main/java/seedu/address/logic/commands/UpcomingCommand.java
  src/main/java/seedu/address/model/delivery/Quantity.java
Labels: type.Bug, priority.High

#173 Update ScrollPane
  build.gradle
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High, alpha-bug

#176 Edit delivery status comparator
  src/main/java/seedu/address/model/delivery/DeliverySortStatusComparator.java
Labels: type.Bug

#184 Fix bug in FindDelivery command after sorting suppliers
  src/main/java/seedu/address/logic/commands/FindDeliveryCommand.java
Labels: type.Bug, priority.High, alpha-bug

#185 Update UG
  docs/UserGuide.md
  docs/images/findSupplierCommand.png
Labels: priority.High

#180 Set prefHeight for SupplierListCard and DeliveryListCard
  src/main/resources/view/DeliveryListCard.fxml
  src/main/resources/view/SupplierListCard.fxml
Labels: type.Task, priority.Medium

#187 Add FindDelivery command in UserGuide
  docs/UserGuide.md
  docs/images/findDeliveryCommand.png
Labels: type.Task, priority.High

#179 Delete the editCommand
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditSupplierDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditSupplierDescriptorBuilder.java
  src/test/java/seedu/address/testutil/SupplierUtil.java
Labels: priority.High

#190 Throw error message when trying to pair delivery to inactive supplier
  src/main/java/seedu/address/logic/commands/AddDeliveryCommand.java
  src/test/java/seedu/address/logic/commands/AddDeliveryCommandTest.java
  src/test/java/seedu/address/testutil/TypicalDeliveryWrappers.java
Labels: priority.High

#191 Update user guide to include sort delivery command
  docs/UserGuide.md
  docs/images/SortDeliveryCommand.png
  src/main/java/seedu/address/model/delivery/DeliverySortBy.java
Labels: priority.High

#192 Update user guide for Upcoming and AddDelivery commands
  docs/UserGuide.md
  docs/images/upcomingCommand.png
  src/main/java/seedu/address/logic/commands/AddDeliveryCommand.java
  src/main/java/seedu/address/logic/commands/UpcomingCommand.java
Labels: priority.High

#193 Update UG
  docs/UserGuide.md
Labels: type.Task

#203 Update upcoming command message
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/UpcomingCommand.java
Labels: priority.High

#204 Update Mark, Delete and Find Delivery commands in UserGuide
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/MarkDeliveryCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Task, priority.High

#209 Standardise delete commands to display all entries
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteDeliveryCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSupplierCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Bug

#211 Update Architecture sequence diagram and NFRs in DG
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagramMarkSupplier.puml
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindDeliveryCommand.java
  src/test/java/seedu/address/logic/commands/FindDeliveryCommandTest.java
Labels: type.Task, priority.High

#213 Update user stories to developer guide
  docs/DeveloperGuide.md
Labels: type.Task

#215 Update logic component in developer guide
  docs/DeveloperGuide.md
Labels: type.Task

#221 Update model class diagram
  docs/DeveloperGuide.md
  docs/diagrams/DeliveryClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: priority.High

#222 Show duplicate delivery message if cost value is the same
  src/main/java/seedu/address/model/delivery/Cost.java
Labels: type.Bug, priority.High

#220 Fix alpha bugs and Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddDeliveryCommand.java
  src/main/java/seedu/address/logic/commands/AddSupplierCommand.java
  src/main/java/seedu/address/logic/commands/MarkDeliveryCommand.java
  src/main/java/seedu/address/logic/commands/MarkSupplierCommand.java
  src/main/java/seedu/address/logic/commands/SortDeliveryCommand.java
  src/main/java/seedu/address/logic/commands/SortSupplierCommand.java
  src/main/java/seedu/address/logic/parser/AddSupplierCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/delivery/Cost.java
  src/main/java/seedu/address/model/delivery/DateTime.java
  src/main/java/seedu/address/model/delivery/DateTimeAfterInputDatePredicate.java
  src/main/java/seedu/address/model/delivery/DateTimeBeforeInputDatePredicate.java
  src/main/java/seedu/address/model/delivery/Delivery.java
  src/main/java/seedu/address/model/delivery/exceptions/DuplicateDeliveryException.java
  src/main/java/seedu/address/model/supplier/Address.java
  src/main/java/seedu/address/model/supplier/Company.java
  src/main/java/seedu/address/model/supplier/Supplier.java
  src/main/java/seedu/address/model/supplier/SupplierStatus.java
  src/main/java/seedu/address/model/supplier/exceptions/DuplicateSupplierException.java
  src/main/java/seedu/address/model/supplier/predicates/CompanyContainsKeywordPredicate.java
  src/main/java/seedu/address/model/supplier/predicates/NameContainsKeywordPredicate.java
  src/main/java/seedu/address/model/supplier/predicates/ProductContainsKeywordPredicate.java
  src/main/java/seedu/address/model/supplier/predicates/SupplierPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedDelivery.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidSupplierAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalSuppliersAddressBook.json
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/supplier/AddressTest.java
  src/test/java/seedu/address/testutil/DeliveryBuilder.java
  src/test/java/seedu/address/testutil/TypicalSuppliers.java
Labels: type.Task, alpha-bug

#225 Update link for delete supplier in UserGuide
  docs/UserGuide.md
Labels: type.Task, priority.High

#230 Update data json file name
  docs/UserGuide.md
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: type.Task, priority.High

#232 Fix status message bugs
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddDeliveryCommand.java
  src/main/java/seedu/address/logic/commands/AddSupplierCommand.java
  src/main/java/seedu/address/logic/commands/FindDeliveryCommand.java
  src/main/java/seedu/address/logic/commands/FindSupplierCommand.java
  src/main/java/seedu/address/logic/commands/UpcomingCommand.java
  src/main/java/seedu/address/logic/parser/FindDeliveryCommandParser.java
  src/main/java/seedu/address/logic/parser/SortOrder.java
  src/main/java/seedu/address/model/delivery/Cost.java
  src/main/java/seedu/address/model/delivery/DeliverySortBy.java
  src/main/java/seedu/address/model/delivery/Quantity.java
  src/main/java/seedu/address/model/delivery/SupplierIndex.java
  src/main/java/seedu/address/model/product/Product.java
  src/main/java/seedu/address/model/supplier/Company.java
  src/main/java/seedu/address/model/supplier/Email.java
  src/main/java/seedu/address/model/supplier/Name.java
  src/main/java/seedu/address/model/supplier/Phone.java
  src/main/java/seedu/address/model/supplier/SupplierSortBy.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/parser/FindDeliveryCommandParserTest.java
Labels: priority.High

#238 Add sample deliveries
  docs/DeveloperGuide.md
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: type.Task, priority.High

#332 Edit supplier add list delete commands in ug
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
Labels: UG

#341 Update user guide for AddDelivery, mark -d , list -d and upcoming
  docs/UserGuide.md
  docs/images/addDeliveryCommand.png
Labels: priority.High, UG

#339 Update delete, find, sort delivery commands in UserGuide
  docs/UserGuide.md
Labels: type.Task, priority.High

#344 Update model class diagram to be less cluttered
  docs/diagrams/ModelClassDiagram.puml
Labels: DG

#352 Remove BetterModelClassDiagram from DG
  docs/DeveloperGuide.md
Labels: DG

#348 Update user guide to ensure consistency
  docs/UserGuide.md
  src/main/java/seedu/address/model/supplier/Company.java
  src/main/java/seedu/address/ui/SupplierCard.java
Labels: UG

#362 Update Glossary in UserGuide
  docs/UserGuide.md
Labels: type.Task, priority.High

#364 Docs/ug images
  docs/UserGuide.md
  docs/images/addDeliveryCommand.png
  docs/images/addSupplierCommand.png
  docs/images/deleteDeliveryCommand.png
  docs/images/deleteSupplierCommand.png
  docs/images/findDeliveryCommand.png
  docs/images/findSupplierCommand.png
  docs/images/generalCommands/helpCommand.png
  docs/images/intro/jarFile.png
  docs/images/markDeliveryCommand.png
  docs/images/markSupplierCommand.png
  docs/images/sortDeliveriesCommand.png
  docs/images/sortDeliveryCommand.png
  docs/images/sortSupplierCommand.png
  docs/images/upcomingCommand.png
  src/test/java/seedu/address/model/delivery/DeliverySortCostComparatorTest.java
Labels: UG

#357 Add effort section to DG
  docs/DeveloperGuide.md
  docs/_markbind/layouts/default.md
Labels: DG

#360 Update FAQ section of user guide
  docs/UserGuide.md
  docs/images/DataFile.png
  docs/images/UnderlinedData.png
  docs/images/VendorVaultFolder.png
Labels: priority.High, UG

#368 Update DG for line spacing inconsistency
  docs/DeveloperGuide.md
Labels: DG

#370 Update Known Issues in UG
  docs/UserGuide.md
Labels: type.Task, priority.High

#378 Refactor delivery comparator compare method
  src/main/java/seedu/address/model/delivery/Cost.java
  src/main/java/seedu/address/model/delivery/DateTime.java
  src/main/java/seedu/address/model/delivery/DeliverySortBy.java
  src/main/java/seedu/address/model/delivery/DeliverySortCostComparator.java
  src/main/java/seedu/address/model/delivery/DeliverySortDateTimeComparator.java
Labels: type.Task

#373 Improve overall code quality
  README.md
  docs/UserGuide.md
  docs/diagrams/DeleteSupplierSequenceDiagram.puml
  docs/images/Ui.png
  docs/images/findDeliveryCommand.png
  docs/images/findSupplierCommand.png
  docs/images/markDeliveryCommand.png
  docs/images/markSupplierCommand.png
  docs/images/upcomingCommand.png
  docs/index.md
  src/main/java/seedu/address/logic/commands/AddSupplierCommand.java
  src/main/java/seedu/address/logic/commands/SortDeliveryCommand.java
  src/main/java/seedu/address/logic/parser/AddSupplierCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortDeliveryCommandParser.java
  src/main/java/seedu/address/logic/parser/SortOrder.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/delivery/Cost.java
  src/main/java/seedu/address/model/delivery/DateTime.java
  src/main/java/seedu/address/model/delivery/DeliverySortBy.java
  src/main/java/seedu/address/model/delivery/DeliverySortComparator.java
  src/main/java/seedu/address/model/delivery/DeliverySortCostComparator.java
  src/main/java/seedu/address/model/delivery/DeliverySortDateTimeComparator.java
  src/main/java/seedu/address/model/delivery/DeliverySortStatusComparator.java
  src/main/java/seedu/address/model/product/Product.java
  src/main/java/seedu/address/model/supplier/Company.java
  src/main/java/seedu/address/model/supplier/Email.java
  src/main/java/seedu/address/model/supplier/Name.java
  src/main/java/seedu/address/model/supplier/Phone.java
  src/main/java/seedu/address/model/supplier/SupplierSortNameComparator.java
  src/main/java/seedu/address/model/supplier/SupplierStatus.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/JsonAdaptedDelivery.java
  src/main/java/seedu/address/storage/JsonAdaptedProduct.java
  src/main/java/seedu/address/storage/JsonAdaptedSupplier.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/DeliveryCard.java
  src/main/java/seedu/address/ui/SupplierCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/MarkSupplierCommandTest.java
  src/test/java/seedu/address/logic/commands/SortDeliveryCommandTest.java
  src/test/java/seedu/address/logic/parser/AddSupplierCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SortDeliveryCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortOrderTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/delivery/DeliverySortByTest.java
  src/test/java/seedu/address/model/delivery/DeliverySortCostComparatorTest.java
  src/test/java/seedu/address/model/delivery/DeliverySortDateTimeComparatorTest.java
  src/test/java/seedu/address/model/delivery/DeliverySortStatusComparatorTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedSupplierTest.java
  src/test/java/seedu/address/testutil/SupplierUtil.java
Labels: type.Task

#382 Edit model description in DG
  docs/DeveloperGuide.md
Labels: DG
